server:
  port: 9000
spring:
  application:
    name: feign-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#ribbon:
#  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
#  ReadTimeout: 1000   #负载均衡超时时间，默认值5000
#  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
#  MaxAutoRetries: 1     #对当前实例的重试次数，默认0
#  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
# ReactiveFeignClientProperties
reactive:
  feign:
    logger:
      enabled: true
    client:
      config:
        default:
          retry:
            args:
              backoffInMs: 1000
              maxRetries: 1
            builder: reactivefeign.retry.BasicReactiveRetryPolicy.Builder
          options:
            builder: reactivefeign.webclient.WebReactiveOptions.Builder
            readTimeoutMillis: 5000
            writeTimeoutMillis: 10000


hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms